---
apiVersion: storage.deckhouse.io/v1alpha1
kind: LVMVolumeGroup
metadata:
  name: data
spec:
  # For SDS replicated-volume module, use Local VG
  type: Local
  actualVGNameOnTheNode: data
  blockDeviceSelector:
    devicePaths:
      - /dev/sdd
---
apiVersion: storage.deckhouse.io/v1alpha1
kind: ReplicatedStoragePool
metadata:
  name: data
spec:
  type: Local
  lvmVolumeGroups:
    - name: data
---
apiVersion: storage.deckhouse.io/v1alpha1
kind: ReplicatedStorageClass
metadata:
  name: linstor-thin-r2
spec:
  storagePool: data
  reclaimPolicy: Delete
  topology: Ignored
  volumeAccess: Local
