{{- if .Values.virtualization.internal.isReady }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-api-rewriter-kubeconfig
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
data:
  kube-api-rewriter.kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - cluster:
          server: http://127.0.0.1:23915
        name: kube-api-rewriter
    contexts:
      - context:
          cluster: kube-api-rewriter
        name: kube-api-rewriter
    current-context: kube-api-rewriter
{{- end }}
