{{- if ne (dig "dvcr" "serviceIP" "" .Values.virtualization.internal) "" }}
---
    {{- $ca := printf "%s" .Values.virtualization.internal.dvcr.cert.ca }}
    {{- $password :=  printf "admin:%s" (printf "%s" .Values.virtualization.internal.dvcr.passwordRW | b64dec) | b64enc }}
    {{- $registry := include "dvcr.get_registry" (list .) }}
    {{- $endpoint := .Values.virtualization.internal.dvcr.serviceIP }}

apiVersion: deckhouse.io/v1alpha1
kind: NodeGroupConfiguration
metadata:
  name: containerd-dvcr-config.sh
  {{- include "helm_lib_module_labels" (list . (dict "app" "dvcr" )) | nindent 2 }}
spec:
  weight: 31
  nodeGroups: ["*"]
  bundles: ["*"]
  content: |
    # Copyright 2023 Flant JSC
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #      http://www.apache.org/licenses/LICENSE-2.0
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.

    bb-event-on 'registry-ca-changed' '_restart_containerd'
    bb-event-on 'containerd-config-changed' '_restart_containerd'
    _restart_containerd() {
        bb-flag-set containerd-need-restart
    }

    {{ "{{- if and (eq .cri \"Containerd\") (not .registry.registryModuleEnable) }}" }}

    mkdir -p /etc/containerd/conf.d
    bb-sync-file /etc/containerd/conf.d/dvcr-ca.crt - registry-ca-changed << "EOF"
    {{- $ca | nindent 4 }}
    EOF

    bb-sync-file /etc/containerd/conf.d/dvcr.toml - containerd-config-changed << "EOF"
    [plugins]
      [plugins."io.containerd.grpc.v1.cri"]
        [plugins."io.containerd.grpc.v1.cri".registry]
          [plugins."io.containerd.grpc.v1.cri".registry.configs]
            [plugins."io.containerd.grpc.v1.cri".registry.configs."{{ $registry }}"]
            [plugins."io.containerd.grpc.v1.cri".registry.configs."{{ $endpoint }}"]
              [plugins."io.containerd.grpc.v1.cri".registry.configs."{{ $endpoint }}".auth]
                auth = {{  $password | quote }}
              [plugins."io.containerd.grpc.v1.cri".registry.configs."{{ $endpoint }}".tls]
                ca_file = "/etc/containerd/conf.d/dvcr-ca.crt"
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{ $registry }}"]
              endpoint = ["https://{{ $endpoint }}"]
    EOF

    {{- if $registry }}
    rm -rf "/etc/containerd/registry.d/{{ $registry }}"
    rm -rf "/etc/containerd/certs.d/{{ $registry }}"
    {{- end }}

    {{ "{{- else }}" }}

    mkdir -p "/etc/containerd/registry.d/{{ $registry }}"
    mkdir -p "/etc/containerd/certs.d/{{ $registry }}"
    bb-sync-file "/etc/containerd/certs.d/{{ $registry }}/ca.crt" - registry-ca-changed << "EOF"
    {{- $ca | nindent 4 }}
    EOF

    bb-sync-file "/etc/containerd/registry.d/{{ $registry }}/hosts.toml" - containerd-config-changed << "EOF"
    server = "https://{{ $registry }}"
    [host."https://{{ $endpoint }}"]
      capabilities = ["pull", "resolve"]
      ca = "/etc/containerd/certs.d/{{ $registry }}/ca.crt"
    [host."https://{{ $endpoint }}".auth]
      auth = {{  $password | quote }}
    EOF

    rm -f /etc/containerd/conf.d/dvcr.toml

    {{ "{{- end }}" }}

{{- end }}
