---
apiVersion: v1
kind: Service
metadata:
  name: jump-host
  namespace: {{ .Values.namespace }}
  labels:
    e2e.deckhouse.io/run-id: "{{ .Values.namespace }}"
spec:
  type: NodePort
  selector:
    app: jump-host
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222

