{{- if .Values.virtualization.internal.isReady }}
{{- if (.Values.global.enabledModules | has "operator-prometheus-crd") }}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: virtualization-controller
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "virtualization-controller" "prometheus" "main")) | nindent 2 }}
spec:
  honorLabels: true
  authorization:
    credentials:
      key: token
      name: prometheus-token
  scheme: HTTPS
  tlsConfig:
    insecureSkipVerify: true
  staticConfigs:
    - targets: ['virtualization-controller-metrics.d8-{{ .Chart.Name }}.svc.{{ .Values.global.discovery.clusterDomain }}.:8080']
  metricsPath: '/metrics'

{{- end }}
{{- end }}
