apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachineBlockDeviceAttachment
metadata:
  name: vmd-blank-attachment
spec:
  virtualMachineName: linux-vm
  blockDevice:
    type: VirtualDisk
    virtualDisk:
      name: vmd-blank
