---
apiVersion: v1
kind: Secret
metadata:
  name: dhctl-regcred
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.deckhouse.registryDockerCfg | quote }}

