---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualImage
metadata:
  name: image
  namespace: {{ .Values.namespace }}
  labels:
    e2e.deckhouse.io/run-id: "{{ .Values.namespace }}"
spec:
  storage: ContainerRegistry
  dataSource:
    type: HTTP
    http:
      url: {{ .Values.image.url }}
