{{- if .Values.virtualization.internal.isReady }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:manage:virtualization:superadmin
  labels:
    heritage: deckhouse
    module: virtualization
    rbac.deckhouse.io/use-role: user
    rbac.deckhouse.io/kind: manage
    rbac.deckhouse.io/level: subsystem
    rbac.deckhouse.io/subsystem: virtualization
    rbac.deckhouse.io/aggregate-to-all-as: superadmin
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.deckhouse.io/kind: manage
        rbac.deckhouse.io/aggregate-to-virtualization-as: superadmin
rules: []
{{- end }}
