# Copyright 2025 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Daily CVE tests"
on:
  schedule:
    # Run at 2:00 every night (UTC).
    - cron: "0 02 * * *"
  workflow_dispatch:
    inputs:
      tag_type:
        type: choice
        description: Tag type
        required: false
        options:
          - release
          - dev
      tag_name:
        description: "release version in semver minor format (example: 1.68) or specified tag from dev registry"
        required: false

concurrency:
  group: cve-daily

jobs:
  cve_scan_daily:
    name: Trivy images check
    runs-on: [self-hosted, large]
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/cve_scan@v6
        with:
          tag: ${{ github.event.inputs.tag_name || 'main' }}
          tag_type: ${{ github.event.inputs.tag_type }}
          module_name: ${{ vars.MODULE_NAME }}
          dd_url: ${{vars.DEFECTDOJO_HOST}}
          dd_token: ${{secrets.DEFECTDOJO_API_TOKEN}}
          prod_registry: ${{vars.TRIVY_REGISTRY}}
          prod_registry_user: ${{ secrets.PROD_READ_REGISTRY_USER }}
          prod_registry_password: ${{ secrets.PROD_READ_REGISTRY_PASSWORD }}
          dev_registry: ${{ vars.DEV_REGISTRY }}
          dev_registry_user: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          dev_registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
          deckhouse_private_repo: ${{vars.DECKHOUSE_PRIVATE_REPO}}
          latest_releases_amount: 5
