# Copyright 2024 Flant JSC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Nightly E2E tests(main)

env:
  CI_COMMIT_REF_NAME: ${{ github.ref_name }}
  GO_VERSION: "1.22.7"
  TIMEOUT: "2h"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

defaults:
  run:
    shell: bash

jobs:
  show_dev_manifest:
    runs-on: ubuntu-latest
    name: Run e2e
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Install ginkgo
        working-directory: ./tests/e2e/
        run: |
          echo "Install ginkgo"
          GINKGO_VERSION=$(go list -f '{{.Version}}' -m github.com/onsi/ginkgo/v2)
          go install "github.com/onsi/ginkgo/v2/ginkgo@${GINKGO_VERSION}"

      - name: Install Deckhouse-cli
        run: |
          echo "Install d8"
          curl -fsSL -o d8-install.sh https://raw.githubusercontent.com/deckhouse/deckhouse-cli/main/d8-install.sh
          bash d8-install.sh

      - uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: https://api.e2e.virtlab.flant.com
          k8s-secret: ${{ secrets.E2E_VIRTUALIZATION_SA_SECRET }}

      - name: Download dependencies
        working-directory: ./tests/e2e/
        run: |
          echo "Download dependencies"
          go mod download

      - name: Run E2E
        id: e2e-tests
        working-directory: ./tests/e2e/
        run: |
          task run:ci -v

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: resources_from_failed_tests
          path: /tmp/e2e_failed__*
          if-no-files-found: ignore

      - name: Send results to Loop
        working-directory: ./tests/e2e/
        if: always()
        run: |
          if [ -z "$SUMMARY" ]; then
            SUMMARY="
            ### :dvp: **DVP $DATE Nightly e2e Tests**

            **Branch:** \`$GITHUB_REF_NAME\`
            **Status: :question: UNKNOWN**

            [:link: GitHub Actions Output]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)
            "
          fi
          echo $SUMMARY
          curl -XPOST -H 'Content-Type: application/json' -d "{\"text\": \"${SUMMARY}\"}" $LOOP_WEBHOOK_URL
        env:
          LOOP_WEBHOOK_URL: ${{ secrets.LOOP_WEBHOOK_URL }}
